version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    #container_name: 'tch-postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    #ports:
    #  - 6432:5432

  blockscout:
    depends_on:
      - db
    #image: domecloud/blockscout-jfin-testnet
    image: domecloud/blockscout-fix-int
    restart: always
    #container_name: 'tch-blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        ETHEREUM_JSONRPC_HTTP_URL: http://95.217.122.150:8545/
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 1
    ports:
      - 4001:4000

